/**
 * Canonical audit action codes. Append new codes at the end; never rename.
 * Each code maps 1:1 with a row in api_audit_log.action.
 */
export type AuditAction =
  | "auth.login_success"
  | "auth.login_failed"
  /** Teto de tentativas barrou antes de chegar ao provedor (issue #64). */
  | "auth.login_rate_limited"
  | "auth.logout"
  | "auth.mfa_enrolled"
  | "auth.mfa_success"
  | "auth.mfa_failed"
  | "auth.recovery_code_used"
  | "nuvemshop.connected"
  | "nuvemshop.disconnected"
  | "nuvemshop.oauth_failed"
  | "nuvemshop.webhook_received"
  | "nuvemshop.webhook_invalid_signature"
  | "lead.created"
  | "lead.updated"
  | "lead.deleted"
  | "lead.moved"
  | "lead.won"
  | "lead.lost"
  | "lead.bulk_action"
  | "contact.created"
  | "contact.updated"
  | "contact.anonymized"
  | "contact.merge_pending"
  | "contact.merged"
  | "lgpd.anonymize_executed"
  | "member.invited"
  | "member.accepted"
  | "member.role_changed"
  | "member.revoked"
  | "token.created"
  | "token.revoked"
  | "profile.updated"
  | "org.updated"
  | "pipeline.config_updated"
  | "mfa.recovery_codes_regenerated"
  | "notification_prefs.changed"
  | "onboarding.welcome_completed"
  | "onboarding.whatsapp_configured"
  | "onboarding.whatsapp_skipped"
  | "onboarding.nuvemshop_skipped"
  | "onboarding.ai_configured"
  | "onboarding.team_invited"
  | "onboarding.completed"
  | "tenant.onboarded"
  | "conversation.created"
  | "conversation.claimed"
  | "conversation.transferred"
  | "conversation.released"
  | "conversation.closed"
  | "conversation.tags_changed"
  | "contact.tags_changed"
  | "lead.tags_changed"
  | "message.sent"
  | "message.received"
  // Uma rodada do cron `recover-stuck-messages` que de fato marcou mensagem
  // como falha (rodada vazia não vira linha — varredura não é mutação).
  | "message.recover_stuck_run"
  | "contact.blocked"
  | "ai.handoff_triggered"
  | "ai.reactivated_by_agent"
  | "conversation.usable_for_rag_toggled"
  | "rag.conversations_batch_run"
  | "lgpd.redact_received"
  | "lgpd.data_request_received"
  | "lgpd.store_redact_received"
  | "lgpd.export_generated"
  | "lgpd.export_delivered"
  | "lgpd.export_failed"
  | "lgpd.redact_executed"
  | "lgpd.redact_skipped_already_anonymized"
  | "lgpd.redact_no_local_footprint"
  | "lgpd.redact_completed"
  | "lgpd.redact_failed"
  | "lgpd.tenant_redacted"
  | "lgpd.consent_changed"
  | "lgpd.manually_approved"
  | "webhook.hmac_invalid"
  | "lgpd.sla_alarm_triggered"
  | "lgpd.sla_watcher_run"
  | "platform_admin.inbox_listed"
  | "platform_admin.conversation_viewed"
  | "platform_admin.tenants_listed"
  | "platform_admin.tenant_viewed"
  | "tenant.created_by_platform_admin"
  | "platform_admin.tenant_health_viewed"
  | "platform_admin.impersonate_started"
  | "platform_admin.impersonate_ended"
  | "platform_admin.impersonate_misconfigured"
  | "tenant.suspended"
  | "tenant.reactivated"
  | "platform_admin.audit_listed"
  | "platform_admin.audit_entry_viewed"
  | "platform_admin.lgpd_listed"
  | "platform_admin.lgpd_request_viewed"
  | "platform_admin.incidents_listed"
  | "platform_admin.incident_viewed"
  | "incident.resolved"
  | "platform_admin.usage_viewed"
  | "platform_admin.users_listed"
  | "platform_admin.user_viewed"
  | "platform_admin.platform_admins_listed"
  | "mcp.tool_called"
  | "ai.credential_created"
  | "ai.credential_deleted"
  | "ai.credential_revalidated"
  | "ai_agent.created"
  | "ai_agent.updated"
  | "ai_agent.archived"
  | "ai_agent.duplicated"
  | "ai_agent.paused"
  | "ai_agent.published"
  | "ai_agent.version_created"
  | "ai_agent.version_updated"
  | "ai_agent.tested"
  | "ai_agent.reverted"
  | "ai.dispatcher_run"
  | "ai.pacing_knobs_updated"
  | "ai.inbox_item_status_changed"
  | "ai.flywheel_proposal_applied"
  | "ai.org_memory_published"
  | "ai.org_memory_entry_created"
  | "ai.org_memory_entry_updated"
  | "ai_agent.run_started"
  | "ai_agent.run_completed"
  | "ai_agent.run_failed"
  | "channel.connected"
  | "channel.reconnected"
  // Duas ações distintas de propósito: `deleted` apagou a linha (canal virgem),
  // `archived` só a escondeu porque conversas/mensagens ainda a referenciam.
  // A auditoria precisa distinguir o que sumiu do que continua no banco.
  | "channel.deleted"
  | "channel.archived"
  // Contraparte de `archived`: a linha escondida voltou à vida (reconexão do
  // canal oficial, retomada do pareamento). Sem ela o histórico registra a
  // exclusão e cala sobre o canal ter voltado a receber e enviar. Emitida por
  // `lib/channels/reactivate.ts` — o único caminho de volta, e é o que faz a
  // frase acima valer para os DOIS casos em vez de para o que lembraram.
  | "channel.reactivated"
  | "authz.denied"
  | "team.role_changed"
  | "leads.bulk_assigned"
  | "attendant.availability_changed"
  | "routing.config_changed"
  | "routing.worker_run"
  | "attendant.heartbeat_swept"
  | "webhook.source_created"
  | "webhook.source_updated"
  | "webhook.source_deleted"
  | "webhook.lead_received"
  | "webhook.inbound_invalid_signature"
  | "automation.rule_created"
  | "automation.rule_updated"
  | "automation.rule_deleted"
  | "automation.rule_executed"
  | "automation.run_resent"
  | "ai.skill_imported"
  | "ai.skill_installed"
  | "ai.skill_uninstalled"
  | "ai.router_created"
  | "ai.router_updated"
  | "ai.router_deleted"
  | "ai.router_members_updated"
  | "followup_flow.created"
  | "followup_flow.updated"
  | "followup_flow.published"
  | "followup_flow.disabled"
  | "followup_flow.rolled_back"
  | "followup.worker_run"
  | "followup.silence_sweep_run"
  | "followup_enrollment.created"
  | "followup_enrollment.cancelled"
  | "template.created"
  | "template.updated"
  | "template.deleted"
  | "auth.signup_requested"
  | "auth.signup_failed"
  | "auth.signup_confirmed"
  | "auth.signup_provision_failed"
  | "auth.email_link_rejected"
  | "auth.password_reset_requested"
  | "auth.password_reset_request_failed"
  | "auth.password_reset_completed"
  | "auth.password_reset_failed"
  | "tenant.created_by_signup"
  | "conversation.snoozed"
  | "conversation.snooze_cancelled"
  | "conversation.snooze_watcher_run"
  | "conversation.note_added"
  | "conversation.note_deleted"
  | "ai.case_replied"
  // O agente participando do chamado — separado de `ai.case_replied` (a pessoa
  // respondendo) porque juntar os dois apagaria justamente quem agiu.
  | "ai.case_noted_by_agent"
  | "ai.case_closed_by_agent"
  | "pipeline.agent_mapping_updated"
  | "pipeline.stage_created"
  | "pipeline.stage_updated"
  | "pipeline.stage_archived"
  | "pipeline.created"
  | "pipeline.updated"
  | "pipeline.archived"
  // Só existe para o funil que nunca recebeu negócio: com histórico, a operação
  // vira `pipeline.archived` e a linha continua no banco.
  | "pipeline.deleted"
  | "system.update_requested"
  | "system.update_finished"
  // IA 360 · wave 2 — o retorno agendado deixou de ser exclusividade do motor e
  // virou capacidade configurável. `followup_enrollment.*` é o motor de FLUXOS;
  // estas duas são a PROMESSA avulsa (cron_jobs), que é outra coisa e precisava
  // de código próprio para não somar duas grandezas no mesmo relatório.
  | "followup.scheduled"
  | "followup.cancelled"
  | "lead.reactivation_proposed";
